---
title: "Composite Legislative Index"
author: "Authored by: Catalyst California"
date: "9/10/2025"
output:
  html_document:
    number_sections: no
    theme: flatly
    toc: yes
    toc_depth: 3
    toc_float: yes
subtitle: 'Draft Visuals'
---

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<style type="text/css">
  h1{
  font-family: Rubik;
  }
  h2{
  font-family: Rubik;
  }
  h3{
  font-family: Rubik;
  }
  a{
  font-family: Rubik;
  }
  ul{
  font-family: Rubik;
  }
  ol{
  font-family: Rubik;
  }
  body{
  font-family: Rubik;
  font-size: 15px;
}
p{
  font-family: Rubik;
  font-size: 15px;
}

</style>




```{r leg data, echo=FALSE, cache=TRUE, include=FALSE}
knitr::opts_chunk$set(comment = FALSE, message = FALSE, warning = FALSE, echo = FALSE)

# set up workspace
packages <- c("DT", "RPostgres", "formattable", "knitr", "dplyr", "htmltools", "tidyr", "stringr", "scales", "colorspace", "sf")  

install_packages <- packages[!(packages %in% installed.packages()[,"Package"])] 

if(length(install_packages) > 0) { 
  install.packages(install_packages) 
  
} else { 
  
  print("All required packages are already installed.") 
} 

for(pkg in packages){ 
  library(pkg, character.only = TRUE) 
} 

# load PostgreSQL driver
source("W:\\RDA Team\\R\\credentials_source.R")
con <- connect_to_db("racecounts")

##### UPDATE EACH YEAR ####
rc_schema <- 'v7'
rc_yr <- '2025'

# setwd("W:/Project/RACE COUNTS/2025_v7/Visualizations/") 

#### Data Prep Steps ####

### Load index data ###

leg_pop <- dbGetQuery(con, paste0("SELECT * FROM ", rc_schema, ".arei_race_multigeo WHERE geolevel IN ('sldu', 'sldl')")) %>%
  select(-c(name, nh_other_pop, nh_twoormor_pop, swanasa_pop, starts_with("pct_")))

leg_index <- dbGetQuery(con, paste0("SELECT * FROM ", rc_schema, ".arei_composite_index_leg_", rc_yr)) %>%
  left_join(leg_pop, by = c("leg_id" = "geoid", "geolevel" = "geolevel")) %>%
  mutate(leg_name = gsub("State ", "", leg_name))

# drop unneeded cols and cities w/o index scores
leg_index <- leg_index %>% select(leg_name, geolevel, ends_with("pop"), disparity_z, disparity_rank, performance_z, performance_rank, quadrant)

# order table by disparity_rank and reorder cols
leg_index <- arrange(leg_index, -desc(disparity_rank))
leg_index <- leg_index %>% select(leg_name, geolevel, disparity_rank, disparity_z, performance_rank, performance_z, quadrant, everything())
leg_index_table <- leg_index %>% mutate(disp_z_rnd = round(disparity_z, 2), perf_z_rnd = round(performance_z, 2)) %>%
  select(-disparity_z, -performance_z) %>%
  relocate(disp_z_rnd, .after = disparity_rank) %>%
  relocate(perf_z_rnd, .after = performance_rank)
```


```{r leg data table, echo=FALSE, cache=TRUE}

## table fx ##
leg_index_fx <- function(x, gl) {
  # x = index dataframe, gl = 'sldu' or 'sldl'

x <- x %>% filter(geolevel == gl) %>% select(-geolevel)
  
index_table <- datatable(x,
    class = 'cell-border stripe',
    colnames=c(
    'District'= 'leg_name',
    'Disparity Rank' = 'disparity_rank',
    'Disparity Z-Score' = 'disp_z_rnd',
    'Outcome Rank' = 'performance_rank',
    'Outcome Z-Score' = 'perf_z_rnd',
    'Category' = 'quadrant', 
    'Population' = 'total_pop',
    'AIAN Population' = 'aian_pop',
    'Asian Population' = 'nh_asian_pop',
    'Black Population' = 'nh_black_pop',
    'Latinx Population'= 'latino_pop',
    'NHPI Population' = 'pacisl_pop',
    'SWANA Population' = 'swana_pop',
    'White Population' = 'nh_white_pop'
     ),
    style ='default',
    rownames = FALSE,
    filter ='top',
    extensions = c(
      # 'Scroller',
      # 'FixedHeader',
                   'Buttons',
                   'KeyTable', 'FixedColumns'),
    
    options = list(
      dom = 'Bfrtip',
      buttons = c('csv','excel'),
    pageLength = 15,
    autoWidth = TRUE,
    scrollX = T,
    scroller = TRUE
      # columnDefs = list(list(width = '200px', targets = c(1,23))),
    #, searchHighlight = TRUE
    )
    ,
    caption = htmltools::tags$caption(
    style = 'caption-side: bottom; text-align: left;',
    htmltools::strong('Z-scores range from -1 to 1. Disparity rank of 1 means most racially disparate. An outcome rank of 1 means best overall outcomes.'))
    )

return(index_table)

  }

```


### RC 2025: Senate Index Table

```{r sen tables, echo=FALSE, cache=TRUE}

sen_table <- leg_index_fx(leg_index_table, 'sldu')
sen_table

```

### RC 2025: Assembly Index Table

```{r assm tables, echo=FALSE, cache=TRUE}

assm_table <- leg_index_fx(leg_index_table, 'sldl')
assm_table

```

```{r scatter fx, echo=FALSE, cache=TRUE, include=FALSE}
## NOTE: Data viz below based on: W:\Project\RACE COUNTS\2022_v4\Visualizations\RC_2022_Indexes.RMD ###

knitr::opts_chunk$set(comment = FALSE, message = FALSE, warning = FALSE, echo = FALSE)

#Set up workspace
packages <- c("DT", "RPostgres", "formattable","knitr","dplyr","htmltools","tidyr","stringr","scales","colorspace","sf", "leaflet",
"rgdal","rpostgis","RColorBrewer","ggplot2","scales","highcharter","here","htmltools","devtools","broom","kableExtra","reshape2")  

install_packages <- packages[!(packages %in% installed.packages()[,"Package"])] 

if(length(install_packages) > 0) { 
  install.packages(install_packages) 
  
} else { 
  
  print("All required packages are already installed.") 
} 

for(pkg in packages){ 
  library(pkg, character.only = TRUE) 
} 

options(scipen=999)
options(highcharter.theme = hc_theme_smpl(tooltip = list(valueDecimals = 2)))


### LEG INDEX SCATTERPLOT FX ###
leg_index_scatter <- function(x, gl, t) {
# x = index data, gl = 'sldu' or 'sldl', t = theme

x <- x %>% filter(geolevel == gl) %>% select(-geolevel)
    
c_chart_index <- x %>%
    hchart("scatter", 
    hcaes(x=disparity_z, y=performance_z, size=total_pop, group=quadrant),
      tooltip = 
         list(pointFormat = 
                "<strong>City: </strong>{point.leg_name} <br><strong>Disparity Rank: </strong>{point.disparity_rank} <br><strong>Outcome Rank: </strong>{point.performance_rank} <br><strong>Population: </strong>{point.total_pop:,.0f}")) %>%
  #hc_title(text = paste0("City Composite Index: ", r)) %>%
  hc_xAxis(title = list(text = "Disparity Z-Score"), max = 1.2, min = -1.2, tickInterval = .5) %>% 
  hc_yAxis(title = list(text = "Outcome Z-Score"), max = 1.2, min = -1.2, tickInterval = .5) %>% 
  hc_caption(
    text = "Data source: Various",
    align = "center"
     ) %>% hc_size(height=700,width=700) 


### ADD RC THEME ###
rc_theme <- hc_theme(
    # race counts colors
  colors = c("orange", "#800080", "red", "yellow"),
  chart = list(
    backgroundColor = "#F7F7F7", # RC white
    style = list(
          fontFamily = "Rubik") 
  ),
  title = list(
    style = list(
      color = "#070024",
      fontFamily = "Rubik")
  ),
  subtitle = list(
    style = list(
      color = "#8E8C8F", # medium grey
      fontFamily = "Rubik")
  ),
  caption = list(
    style = list(
      color = "#8E8C8F",
      fontFamily = "Rubik")
  ),
    axis = list(
    style = list(
      color = "#8E8C8F",
      fontFamily = "Rubik")
  ),
  legend = list(
    itemStyle = list(
      fontFamily = "Rubik",
      color = "#070024"),
    itemHoverStyle = list(
       fontFamily = "Rubik",
      color = "#070024")
  ))


c_chart_index <-  hc_add_theme(c_chart_index, rc_theme) 

return(c_chart_index)
}



# Add commas to long numbers
lang <- getOption("highcharter.lang")
lang$thousandsSep <- ","
options(highcharter.lang = lang)

```

### Senate Composite Index Scatterplot

```{r sen comp scatter, echo=FALSE}
sen_comp_scatter <- leg_index_scatter(leg_index, 'sldu', rc_theme)
#sen_comp_scatter <- sen_comp_scatter %>% hc_title(text = "Senate Composite Index")

sen_comp_scatter

```

### Assembly Composite Index Scatterplot

```{r assm comp scatter, echo=FALSE}

assm_comp_scatter <- leg_index_scatter(leg_index, 'sldl', rc_theme)
#assm_comp_scatter <- assm_comp_scatter %>% hc_title(text = "Assembly Composite Index")

assm_comp_scatter

```

